services:
  db:
    image: percona/percona-server
    container_name: retail-prices-comparer-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: app-retails
      MYSQL_USER: dsw
      MYSQL_PASSWORD: dsw
    volumes:
      - retail-prices-comparer-data:/var/lib/mysql

volumes:
  retail-prices-comparer-data: