GET http://localhost:3000/Retail

###
GET http://localhost:3000/Retail/2

###
POST http://localhost:3000/Retail
Content-Type: application/json

{
  "retailId": 3,
  "retailName": "Libertad"
  }

###
PUT http://localhost:3000/Retail/2
Content-Type: application/json

{
  "retailName": "Libertad"
  }

###
DELETE http://localhost:3000/Retail/2